### ISSUE TITLE
Game crashes after installing Rubidium

### ISSUE THREAD

**Issue by Basketball985** [FiniteReality/embeddium#119]
Heya, I play on a fairly big modpack, I switched to the Embeddium mod from Rubidium for compatibility reasons, now when I launch embeddium I get this issue: 
[Embeddium crash.txt](https://github.com/embeddedt/embeddium/files/13466437/Embeddium.crash.txt)

**Comment by embeddedt** [comment]
Please provide the `latest.log` file. This crash appears likely to be caused by an addon that uses Sodium internals and hasn't updated to the latest version.

**Comment by YourLocalMeatman** [comment]
Yea, I got the same error, and for some reason, here's the pastebin: https://pastebin.com/0xuQA5Rq

**Comment by embeddedt** [comment]
@YourLocalMeatman Your issue appears to be an outdated Oculus version.

**Comment by YourLocalMeatman** [comment]
Oh ok cool... Ima try updating it, gimme a sec

**Comment by YourLocalMeatman** [comment]
So it worked but when I tried to log into a world, I got this error: (since pastebin said it was too large) file:///C:/Users/tewsr/AppData/Roaming/.minecraft/logs/latest.log

**Comment by embeddedt** [comment]
Can't see that log file, you will have to upload it to another site.

**Comment by YourLocalMeatman** [comment]
[gist:46753d1a543ab430cc1c7c6907ea1d90](https://gist.github.com/YourLocalMeatman/46753d1a543ab430cc1c7c6907ea1d90)

**Comment by embeddedt** [comment]
That error appears unrelated to Embeddium, because it happened on the integrated server, not the client.

```
[29Nov2023 10:48:52.442] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.UnsupportedOperationException: null
	at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:264) ~[guava-31.1-jre.jar%23109!/:?]
	at net.mehvahdjukaar.supplementaries.common.entities.trades.ModVillagerTrades.lambda$init$5(ModVillagerTrades.java:235) ~[supplementaries-1.20-2.5.28.jar%23589!/:?]
	at net.mehvahdjukaar.moonlight.api.platform.forge.RegHelperImpl.lambda$registerVillagerTrades$10(RegHelperImpl.java:204) ~[moonlight-1.20-2.8.16-forge.jar%23543!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.common.VillagerTradingManager.postVillagerEvents(VillagerTradingManager.java:78) ~[forge-1.20.1-47.2.6-universal.jar%23623!/:?]
	at net.minecraftforge.common.VillagerTradingManager.loadTrades(VillagerTradingManager.java:44) ~[forge-1.20.1-47.2.6-universal.jar%23623!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:98) ~[forge-1.20.1-47.2.6-universal.jar%23623!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23618!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23618!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23618!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
