### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by SireOfTheQuags** [FiniteReality/embeddium#121]
I just crashed out of nowhere and Not Enough Crashes said it was caused by this mod

[crash-2023-11-27_00.17.58-client.txt](https://github.com/embeddedt/embeddium/files/13468400/crash-2023-11-27_00.17.58-client.txt)

**Comment by embeddedt** [comment]
```
Caused by: java.lang.OutOfMemoryError
	at org.lwjgl.system.MemoryUtil.nmemReallocChecked(MemoryUtil.java:496) ~[lwjgl-3.3.1.jar%23153!/:build 7] {re:mixin}
	at org.lwjgl.system.MemoryUtil.memRealloc(MemoryUtil.java:529) ~[lwjgl-3.3.1.jar%23153!/:build 7] {re:mixin}
	at me.jellysquid.mods.sodium.client.render.chunk.vertex.builder.ChunkMeshBufferBuilder.setBufferSize(ChunkMeshBufferBuilder.java:57) ~[embeddium-0.2.10+mc1.20.1.jar%23321!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.vertex.builder.ChunkMeshBufferBuilder.start(ChunkMeshBufferBuilder.java:65) ~[embeddium-0.2.10+mc1.20.1.jar%23321!/:?] {re:classloading}
```

This likely means your computer ran out of memory (either too many things open, or another mod has a memory leak). I don't think it's Embeddium's fault - try reducing your heap size slightly, or closing other applications.
