### ISSUE TITLE
Array Index Out Of Bounds Exception crash

### ISSUE THREAD

**Issue by Syndrick** [FiniteReality/embeddium#128]
### Bug Description

When ever I am far away from my base, i'll occasionally get this crash. I'm not 100% certain it's embeddium causing it, but I saw in the recent patch notes that you fixed this crash, so I thought it'd be best to post this.
Also I really hope a google drive link to the latest log works because github was saying that the file was too big

### Reproduction Steps

So i'm playing with the Create mod, and I have a lot of Create machines at my base. The crash happens when I am far from home and using a train to help make a railroad for said train

### Log File

https://drive.google.com/file/d/1Qd9OlaCjvcKApuibKSml4wQKPHgedKUp/view?usp=sharing

**Comment by embeddedt** [comment]
The crash appears to occur within Flywheel code, so it is not something I can patch in Embeddium.

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 2049
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.9/it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.rehash(Long2ObjectOpenHashMap.java:1297)
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.9/it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.insert(Long2ObjectOpenHashMap.java:249)
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.9/it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.computeIfAbsent(Long2ObjectOpenHashMap.java:449)
	at TRANSFORMER/flywheel@0.6.10-7/com.jozufozu.flywheel.light.WeakContainmentMultiMap.put(WeakContainmentMultiMap.java:56)
	at TRANSFORMER/flywheel@0.6.10-7/com.jozufozu.flywheel.light.LightUpdater.addListener(LightUpdater.java:108)
	at TRANSFORMER/flywheel@0.6.10-7/com.jozufozu.flywheel.light.LightUpdater.tickSerial(LightUpdater.java:61)
	at TRANSFORMER/flywheel@0.6.10-7/com.jozufozu.flywheel.light.LightUpdater.tick(LightUpdater.java:54)
	at TRANSFORMER/flywheel@0.6.10-7/com.jozufozu.flywheel.event.ForgeEvents.tickLight(ForgeEvents.java:34)
	at TRANSFORMER/flywheel@0.6.10-7/com.jozufozu.flywheel.event.__ForgeEvents_tickLight_ClientTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:940)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1875)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
```

When I've seen similar crashes with Flywheel in the past, it is usually caused by mods that incorrectly access client data on the wrong thread, like Entity Culling or Sound Physics. I would recommend removing these mods.

**Comment by Syndrick** [comment]
Alrighty, thank you so much. I'll try removing those
