### ISSUE TITLE
Incompatible with Enigmatica 6: Expert modpack

### ISSUE THREAD

**Issue by snpdzk** [FiniteReality/embeddium#251]
### Reproduction Steps

Install Enigmatica 6: Expert modpack and embeddium,join server,then crashes

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14814137/latest.log)

**Comment by embeddedt** [comment]
This is a bug in Mantle/Tinkers' Construct, not Embeddium. It can also happen without Embeddium installed. The RetexturedModel cache is not thread-safe.

```
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?]
	at slimeknights.mantle.client.model.RetexturedModel$BakedModel.getCachedModel(RetexturedModel.java:184) ~[mantle:1.16.5-1.6.157]
	at slimeknights.mantle.client.model.RetexturedModel$BakedModel.getQuads(RetexturedModel.java:205) ~[mantle:1.16.5-1.6.157]
```

**Comment by embeddedt** [comment]
I have added a patch to ModernFix for the next release, which will fix this bug in Mantle.
