### ISSUE TITLE
embeddium doesn't run with mods

### ISSUE THREAD

**Issue by suichanwa** [FiniteReality/embeddium#263]
### Bug Description

Welp i've made a huge modpack with about 270 mods, when im trying to put the mod it's crush giving me that issue

java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/gui/options/TextProvider

### Reproduction Steps

Time: 4/12/24, 10:43 PM
Description: Initializing game

java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/gui/options/TextProvider
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at me.flashyreese.mods.sodiumextra.client.gui.SodiumExtraGameOptions$ExtraSettings.<init>(SodiumExtraGameOptions.java:260) ~[rubidium-extra-0.4.18+mc1.18.2-build.86.jar%23277!/:0.4.18+mc1.18.2-build.86] {re:mixin,re:classloading}
	at me.flashyreese.mods.sodiumextra.client.gui.SodiumExtraGameOptions.<init>(SodiumExtraGameOptions.java:36) ~[rubidium-extra-0.4.18+mc1.18.2-build.86.jar%23277!/:0.4.18+mc1.18.2-build.86] {re:mixin,re:classloading}
	at me.flashyreese.mods.sodiumextra.client.gui.SodiumExtraGameOptions.load(SodiumExtraGameOptions.java:53) ~[rubidium-extra-0.4.18+mc1.18.2-build.86.jar%23277!/:0.4.18+mc1.18.2-build.86] {re:mixin,re:classloading}
	at me.flashyreese.mods.sodiumextra.client.SodiumExtraClientMod.loadConfig(SodiumExtraClientMod.java:47) ~[rubidium-extra-0.4.18+mc1.18.2-build.86.jar%23277!/:0.4.18+mc1.18.2-build.86] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at me.flashyreese.mods.sodiumextra.client.SodiumExtraClientMod.options(SodiumExtraClientMod.java:36) ~[rubidium-extra-0.4.18+mc1.18.2-build.86.jar%23277!/:0.4.18+mc1.18.2-build.86] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.platform.Window.redirect$zlk000$setSwapInterval(Window.java:572) ~[client-1.18.2-20220404.173914-srg.jar%23326!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium-extra.mixins.json:adaptive_sync.MixinWindow,pl:mixin:APP:sodium-extra.mixins.json:reduce_resolution_on_mac.MixinWindow,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.platform.Window.m_85409_(Window.java:264) ~[client-1.18.2-20220404.173914-srg.jar%23326!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium-extra.mixins.json:adaptive_sync.MixinWindow,pl:mixin:APP:sodium-extra.mixins.json:reduce_resolution_on_mac.MixinWindow,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:542) ~[client-1.18.2-20220404.173914-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%23326!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.0.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.gui.options.TextProvider
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 30 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at me.flashyreese.mods.sodiumextra.client.gui.SodiumExtraGameOptions$ExtraSettings.<init>(SodiumExtraGameOptions.java:260) ~[rubidium-extra-0.4.18+mc1.18.2-build.86.jar%23277!/:0.4.18+mc1.18.2-build.86] {re:mixin,re:classloading}
	at me.flashyreese.mods.sodiumextra.client.gui.SodiumExtraGameOptions.<init>(SodiumExtraGameOptions.java:36) ~[rubidium-extra-0.4.18+mc1.18.2-build.86.jar%23277!/:0.4.18+mc1.18.2-build.86] {re:mixin,re:classloading}
	at me.flashyreese.mods.sodiumextra.client.gui.SodiumExtraGameOptions.load(SodiumExtraGameOptions.java:53) ~[rubidium-extra-0.4.18+mc1.18.2-build.86.jar%23277!/:0.4.18+mc1.18.2-build.86] {re:mixin,re:classloading}
	at me.flashyreese.mods.sodiumextra.client.SodiumExtraClientMod.loadConfig(SodiumExtraClientMod.java:47) ~[rubidium-extra-0.4.18+mc1.18.2-build.86.jar%23277!/:0.4.18+mc1.18.2-build.86] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at me.flashyreese.mods.sodiumextra.client.SodiumExtraClientMod.options(SodiumExtraClientMod.java:36) ~[rubidium-extra-0.4.18+mc1.18.2-build.86.jar%23277!/:0.4.18+mc1.18.2-build.86] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.platform.Window.redirect$zlk000$setSwapInterval(Window.java:572) ~[client-1.18.2-20220404.173914-srg.jar%23326!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium-extra.mixins.json:adaptive_sync.MixinWindow,pl:mixin:APP:sodium-extra.mixins.json:reduce_resolution_on_mac.MixinWindow,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.platform.Window.m_85409_(Window.java:264) ~[client-1.18.2-20220404.173914-srg.jar%23326!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium-extra.mixins.json:adaptive_sync.MixinWindow,pl:mixin:APP:sodium-extra.mixins.json:reduce_resolution_on_mac.MixinWindow,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:542) ~[client-1.18.2-20220404.173914-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}

### Log File

[crash-2024-04-12_22.43.49-client.txt](https://github.com/embeddedt/embeddium/files/14962913/crash-2024-04-12_22.43.49-client.txt)

**Comment by embeddedt** [comment]
I am unable to reproduce this issue with the latest versions of Embeddium (0.3.12) & Rubidium Extra (0.4.18) installed by themselves on 1.18.2. You will need to narrow this down some more as I cannot debug 270 mods.
