### ISSUE TITLE
NPE in ClonedChunkSectionCache#cleanup line 31

### ISSUE THREAD

**Issue by Swordstone86** [FiniteReality/embeddium#271]
### Bug Description

Me and some friends are running into this crash with Embeddium on a server modpack using Embeddium 0.7.1 (seems to be [this release.](https://github.com/embeddedt/embeddium/releases/tag/neoforge-20.2-final)) The modpack in question is [Aether Enhanced](https://modrinth.com/modpack/aether-enhanced), in case any of the other mods in the pack might be causing this.

```
[Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "me.jellysquid.mods.sodium.client.world.cloned.ClonedChunkSection.getLastUsedTimestamp()" because "entry" is null
	at me.jellysquid.mods.sodium.client.world.cloned.ClonedChunkSectionCache.lambda$cleanup$0(ClonedChunkSectionCache.java:31) ~[embeddium-0.2.1+mc1.20.1.jar%23205!/:?]
	at java.util.Collection.removeIf(Unknown Source) ~[?:?]
	at me.jellysquid.mods.sodium.client.world.cloned.ClonedChunkSectionCache.cleanup(ClonedChunkSectionCache.java:31) ~[embeddium-0.2.1+mc1.20.1.jar%23205!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:273) ~[embeddium-0.2.1+mc1.20.1.jar%23205!/:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:188) ~[embeddium-0.2.1+mc1.20.1.jar%23205!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_194338_(LevelRenderer.java:9704) ~[client-1.20.1-20230612.114412-srg.jar%23232!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1162) ~[client-1.20.1-20230612.114412-srg.jar%23232!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23232!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23232!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23232!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23232!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-1.20.1-47.1.79.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.1.47.jar:47.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```

### Reproduction Steps

Crash occurs randomly while playing with shaders enabled. Unknown if crash happens when shaders are disabled, but multiple people reported this same crash randomly happening, sometimes several times an hour. I've personally seen this crash happen multiple times while the game was completely minimized and I was doing something else entirely.

### Log File

[2024-04-29-41.log](https://github.com/embeddedt/embeddium/files/15157497/2024-04-29-41.log)

**Comment by embeddedt** [comment]
The `ClonedChunkSectionCache` crashes were fixed a long time ago - you are still using Embeddium 0.2.1 which is very old. Upgrading to the newest version should resolve this. Make sure you also update any add-ons (e.g. Oculus, Embeddium Extra).
