### ISSUE TITLE
Java v17 not working

### ISSUE THREAD

**Issue by SilenceRK** [FiniteReality/embeddium#344]
### Bug Description

As was recommended with my last report, I successfully installed Java 17 and tried to run the game, but it crashes repeatedly with the same exit code.

### Reproduction Steps

See log below:

### Log File

Prism Launcher version: 8.4 (official)

Launched instance in online mode

login.microsoftonline.com resolves to:
    [20.190.152.19, 20.190.152.21, 40.126.24.147, 40.126.24.146, 40.126.24.149, 40.126.24.83, 20.190.152.22, 40.126.24.82, 2603:1036:3000:10::4, 2603:1036:3000:18::2, 2603:1036:3000:18::3, 2603:1037:1:8::4, 2603:1036:3000:18::4, 2603:1036:3000:10::5, 2603:1036:3000:10::3, 2603:1037:1:8::6]

session.minecraft.net resolves to:
    [13.107.246.40, 2620:1ec:bdf::40]

textures.minecraft.net resolves to:
    [13.107.246.40, 2620:1ec:bdf::40]

api.mojang.com resolves to:
    [13.107.246.40, 2620:1ec:bdf::40]

Minecraft folder is:
C:/Users/risha/AppData/Roaming/PrismLauncher/instances/1v1/minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 17.0.11, using 64 (amd64) architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/risha/AppData/Roaming/PrismLauncher/instances/1v1/natives

Traits:
traits FirstThreadOnMacOS
traits feature:is_quick_play_multiplayer
traits XR:Initial

Libraries:
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-windows-arm64/3.3.1/lwjgl-glfw-natives-windows-arm64-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.1/lwjgl-glfw-natives-windows-x86-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.1/lwjgl-glfw-natives-windows-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-arm64/3.3.1/lwjgl-jemalloc-natives-windows-arm64-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.1/lwjgl-jemalloc-natives-windows-x86-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.1/lwjgl-jemalloc-natives-windows-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-windows-arm64/3.3.1/lwjgl-natives-windows-arm64-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.1/lwjgl-natives-windows-x86-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-windows/3.3.1/lwjgl-natives-windows-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-windows-arm64/3.3.1/lwjgl-openal-natives-windows-arm64-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.1/lwjgl-openal-natives-windows-x86-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.1/lwjgl-openal-natives-windows-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-windows-arm64/3.3.1/lwjgl-opengl-natives-windows-arm64-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.1/lwjgl-opengl-natives-windows-x86-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.1/lwjgl-opengl-natives-windows-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-windows-arm64/3.3.1/lwjgl-stb-natives-windows-arm64-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.1/lwjgl-stb-natives-windows-x86-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.1/lwjgl-stb-natives-windows-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-arm64/3.3.1/lwjgl-tinyfd-natives-windows-arm64-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.1/lwjgl-tinyfd-natives-windows-x86-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.1/lwjgl-tinyfd-natives-windows-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/io/github/zekerzhayard/ForgeWrapper/prism-2024-02-29/ForgeWrapper-prism-2024-02-29.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/cpw/mods/securejarhandler/2.1.10/securejarhandler-2.1.10.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm/9.7/asm-9.7.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.7/asm-commons-9.7.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.7/asm-tree-9.7.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-util/9.7/asm-util-9.7.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.7/asm-analysis-9.7.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/eventbus/6.0.5/eventbus-6.0.5.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/forgespi/7.0.1/forgespi-7.0.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/coremods/5.1.6/coremods-5.1.6.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/cpw/mods/modlauncher/10.0.9/modlauncher-10.0.9.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/mergetool/1.1.5/mergetool-1.1.5-api.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/fmlloader/1.20.1-47.3.0/fmlloader-1.20.1-47.3.0.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/fmlearlydisplay/1.20.1-47.3.0/fmlearlydisplay-1.20.1-47.3.0.jar
  C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:

Mods:
  [✔] AdvancementPlaques-1.20.1-forge-1.5.1
  [✔] alexscaves-1.1.4
  [✔] alexsdelight-1.5
  [✔] alexsmobs-1.22.8
  [✔] appleskin-forge-mc1.20.1-2.5.1
  [✔] citadel-2.5.4-1.20.1
  [✔] cloudstorage-1.4.0-1.20
  [✔] DistantHorizons-2.1.2-a-1.20.1-forge-fabric
  [✔] embeddium-0.3.24+mc1.20.1
  [✔] FarmersDelight-1.20.1-1.2.4
  [✔] Iceberg-1.20.1-forge-1.1.21
  [✔] Jade-1.20.1-forge-11.9.2
  [✔] jei-1.20.1-forge-15.3.0.8
  [✔] miners_delight-1.20.1-1.2.3
  [✔] nethersdelight-1.20.1-4.0

Params:
  --username  --version 1.20.1 --gameDir C:/Users/risha/AppData/Roaming/PrismLauncher/instances/1v1/minecraft --assetsDir C:/Users/risha/AppData/Roaming/PrismLauncher/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 47.3.0 --fml.mcVersion 1.20.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230612.114412

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4096m, -Xmx8192m, -Duser.language=en]

Minecraft process ID: 10360

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2024-07-09 20:57:13,819 main WARN Advanced terminal features are not available in this environment
[20:57:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Silence316, --version, 1.20.1, --gameDir, C:/Users/risha/AppData/Roaming/PrismLauncher/instances/1v1/minecraft, --assetsDir, C:/Users/risha/AppData/Roaming/PrismLauncher/assets, --assetIndex, 5, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.3.0, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, --width, 854, --height, 480]
[20:57:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.11 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[20:57:14] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[20:57:14] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[20:57:14] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.5
[20:57:14] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.4
[20:57:14] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.3
[20:57:14] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.2
[20:57:14] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.1
[20:57:14] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.0
[20:57:14] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.0 got version 4.0
[20:57:14] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: Intel(R) HD Graphics 2500 GL version 4.0.0 - Build 10.18.10.4885, Intel
[20:57:14] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23150!/ Service=ModLauncher Env=CLIENT
[20:57:15] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\risha\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\fmlcore\1.20.1-47.3.0\fmlcore-1.20.1-47.3.0.jar is missing mods.toml file
[20:57:15] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\risha\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.3.0\javafmllanguage-1.20.1-47.3.0.jar is missing mods.toml file
[20:57:15] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\risha\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.3.0\lowcodelanguage-1.20.1-47.3.0.jar is missing mods.toml file
[20:57:15] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\risha\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\mclanguage\1.20.1-47.3.0\mclanguage-1.20.1-47.3.0.jar is missing mods.toml file
[20:57:15] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 2 dependencies adding them to mods collection
[20:57:18] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[20:57:18] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, C:\Users\risha\AppData\Roaming\PrismLauncher\instances\1v1\minecraft, --assetsDir, C:\Users\risha\AppData\Roaming\PrismLauncher\assets, --uuid, <PROFILE ID>, --username, Silence316, --assetIndex, 5, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480]
[20:57:18] [main/INFO] [Embeddium/]: Loaded configuration file for Embeddium: 63 options available, 0 override(s) found
[20:57:18] [main/INFO] [Embeddium-GraphicsAdapterProbe/]: Searching for graphics cards...
[20:57:18] [main/INFO] [Embeddium-GraphicsAdapterProbe/]: Found graphics card: GraphicsAdapterInfo[vendor=INTEL, name=Intel(R) HD Graphics, version=DriverVersion=10.18.10.4885]
[20:57:19] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[20:57:26] [Datafixer Bootstrap/INFO] [mojang/DataFixerBuilder]: 188 Datafixer optimizations took 850 milliseconds
[20:57:29] [Render thread/WARN] [minecraft/VanillaPackResourcesBuilder]: Assets URL 'union:/C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23186!/assets/.mcassetsroot' uses unexpected schema
[20:57:29] [Render thread/WARN] [minecraft/VanillaPackResourcesBuilder]: Assets URL 'union:/C:/Users/risha/AppData/Roaming/PrismLauncher/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23186!/data/.mcassetsroot' uses unexpected schema
[20:57:29] [Render thread/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:57:29] [Render thread/INFO] [minecraft/Minecraft]: Setting user: Silence316
[20:57:29] [Render thread/INFO] [minecraft/Minecraft]: Backend library: LWJGL version 3.3.1 build 7
[20:57:29] [Render thread/INFO] [Embeddium-PostlaunchChecks/]: OpenGL Vendor: Intel
[20:57:29] [Render thread/INFO] [Embeddium-PostlaunchChecks/]: OpenGL Renderer: Intel(R) HD Graphics 2500
[20:57:29] [Render thread/INFO] [Embeddium-PostlaunchChecks/]: OpenGL Version: 4.0.0 - Build 10.18.10.4885
[20:57:30] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 47.3.0, for MC 1.20.1 with MCP 20230612.114412
[20:57:30] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v47.3.0 Initialized
[20:57:30] [modloading-worker-0/INFO] [me.je.li.lo.PluginCaller/]: Sending ConfigManager...
[20:57:30] [modloading-worker-0/INFO] [me.je.li.lo.PluginCaller/]: Sending ConfigManager took 3.338 ms
[20:57:34] [Render thread/INFO] [co.gi.al.al.AlexsMobs/]: loaded in block colorizer
[20:57:34] [Render thread/INFO] [co.gi.al.al.AlexsCaves/]: loaded in item colorizer
[20:57:34] [Render thread/INFO] [co.gi.al.al.AlexsMobs/]: loaded in item colorizer
[20:57:34] [Render thread/INFO] [co.gi.al.cl.CloudStorage/]: loaded in item colorizer
[20:57:35] [Render thread/INFO] [GameRenderer/]: Starting up renderer (forge)
[20:57:35] [Render thread/WARN] [GameRenderer/]: Dependency setup is not done yet, skipping renderer this startup event!
[20:57:35] [Render thread/INFO] [minecraft/ReloadableResourceManager]: Reloading ResourceManager: vanilla, mod_resources
[20:57:35] [Worker-Main-1/INFO] [minecraft/UnihexProvider]: Found unifont_all_no_pua-15.0.06.hex, loading
[20:57:35] [Worker-Main-2/WARN] [minecraft/SoundManager]: File alexscaves:sounds/mob/luxtructosaurus/luxtructosaurus_snort_0.ogg does not exist, cannot add it to event alexscaves:luxtructosaurus_snort
[20:57:35] [Worker-Main-2/WARN] [minecraft/SoundManager]: File alexscaves:sounds/mob/luxtructosaurus/luxtructosaurus_snort_1.ogg does not exist, cannot add it to event alexscaves:luxtructosaurus_snort
[20:57:35] [Worker-Main-2/WARN] [minecraft/SoundManager]: File alexscaves:sounds/mob/luxtructosaurus/luxtructosaurus_snort_2.ogg does not exist, cannot add it to event alexscaves:luxtructosaurus_snort
[20:57:35] [Worker-Main-2/WARN] [minecraft/SoundManager]: File alexscaves:sounds/mob/luxtructosaurus/luxtructosaurus_breathe_0.ogg does not exist, cannot add it to event alexscaves:luxtructosaurus_breathe
[20:57:35] [Worker-Main-2/WARN] [minecraft/SoundManager]: File alexscaves:sounds/mob/luxtructosaurus/luxtructosaurus_breathe_1.ogg does not exist, cannot add it to event alexscaves:luxtructosaurus_breathe
[20:57:35] [Worker-Main-2/WARN] [minecraft/SoundManager]: File alexscaves:sounds/mob/luxtructosaurus/luxtructosaurus_breathe_2.ogg does not exist, cannot add it to event alexscaves:luxtructosaurus_breathe
[20:57:36] [Worker-Main-2/ERROR] [minecraft/Util]: Invalid path in pack: miners_delight:textures/item/Lunchbox_fill.png, ignoring
[20:57:36] [Worker-Main-2/ERROR] [minecraft/Util]: Invalid path in pack: miners_delight:textures/item/Lunchbox.png, ignoring
[20:57:36] [Worker-Main-2/ERROR] [minecraft/Util]: Invalid path in pack: miners_delight:textures/item/Launchbox_fill.png, ignoring
[20:57:36] [Worker-Main-2/ERROR] [minecraft/Util]: Invalid path in pack: miners_delight:textures/item/Launchbox.png, ignoring
[20:57:37] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[20:57:37] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: UP_TO_DATE Current: 47.3.0 Target: null
[20:57:37] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [iceberg] Starting version check at https://mc-update-check.anthonyhilyard.com/520110
[20:57:52] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
java.net.http.HttpTimeoutException: request timed out
	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:571) ~[java.net.http:?] {}
	at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123) ~[java.net.http:?] {}
	at net.minecraftforge.fml.VersionChecker$1.openUrlString(VersionChecker.java:139) ~[fmlcore-1.20.1-47.3.0.jar%23187!/:?] {}
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:177) ~[fmlcore-1.20.1-47.3.0.jar%23187!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) ~[fmlcore-1.20.1-47.3.0.jar%23187!/:?] {}
[20:57:52] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [advancementplaques] Starting version check at https://mc-update-check.anthonyhilyard.com/499826
[20:58:07] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
java.net.http.HttpTimeoutException: request timed out
	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:571) ~[java.net.http:?] {}
	at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123) ~[java.net.http:?] {}
	at net.minecraftforge.fml.VersionChecker$1.openUrlString(VersionChecker.java:139) ~[fmlcore-1.20.1-47.3.0.jar%23187!/:?] {}
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:177) ~[fmlcore-1.20.1-47.3.0.jar%23187!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) ~[fmlcore-1.20.1-47.3.0.jar%23187!/:?] {}
Clipboard copy at: 09 Jul 2024 20:58:13 -0400

**Comment by embeddedt** [comment]
There is no crash in this log file, so I am unable to diagnose it with the exit code alone.

**Comment by embeddedt** [comment]
Closing as this is not actionable with the given information and the issue tracker is intended for bug reports, not support requests. Please join the [Discord server](https://discord.gg/rN9Y7caguP) and ask for assistance in `#mod-support` if you are still having problems launching the game.
