### ISSUE TITLE
There is no `embeddium.mixins.json` found in the version 0.3.32+ from the maven

### ISSUE THREAD

**Issue by Yefancy** [FiniteReality/embeddium#394]
### Bug Description

mc version 1.20.1
There is no `embeddium.mixins.json` found in the version 0.3.32+ from the maven jars

### Reproduction Steps

import mode via
```gradle
modImplementation("org.embeddedt:embeddium-1.20.1:0.3.32-beta.64+mc1.20.1")
```

### Log File

```console
Caused by: java.lang.IllegalArgumentException: The specified resource 'embeddium.mixins.json' was invalid or could not be read
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1282)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 25 more
```

**Comment by Yefancy** [comment]
0.3.31+ includes it
