### ISSUE TITLE
World won't launch, game freezes

### ISSUE THREAD

**Issue by Ladocterus** [FiniteReality/embeddium#73]
World loads, but moment it's done it says "saving terrain.
In the logs it still says I joined game, but the game says "it can't keep up", having to force shut it down.
[Embeddium_cant_launch_world.log](https://github.com/embeddedt/embeddium/files/13041615/Embeddium_cant_launch_world.log)
using [1.20.1] Embeddium 0.2.2

**Comment by embeddedt** [comment]
It's a crash - the game just doesn't close for some reason.

```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [snowrealmagic.mixins.json:sodium.BlockRendererAccess] from phase [DEFAULT] in config [snowrealmagic.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	... 58 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching getLightingMode(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/client/resources/model/BakedModel;Lnet/minecraft/world/level/BlockAndTintGetter;Lnet/minecraft/core/BlockPos;)Lme/jellysquid/mods/sodium/client/model/light/LightMode; in me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderer for snowrealmagic.mixins.json:sodium.BlockRendererAccess->@Invoker[METHOD_PROXY]::callGetLightingMode(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/client/resources/model/BakedModel;Lnet/minecraft/world/level/BlockAndTintGetter;Lnet/minecraft/core/BlockPos;)Lme/jellysquid/mods/sodium/client/model/light/LightMode; [INJECT Applicator Phase -> snowrealmagic.mixins.json:sodium.BlockRendererAccess -> Apply Accessors ->  -> Locate -> snowrealmagic.mixins.json:sodium.BlockRendererAccess->@Invoker[METHOD_PROXY]::callGetLightingMode(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/client/resources/model/BakedModel;Lnet/minecraft/world/level/BlockAndTintGetter;Lnet/minecraft/core/BlockPos;)Lme/jellysquid/mods/sodium/client/model/light/LightMode;]
```

You need to update Snow Real Magic to 9.0.2 or later.
