### ISSUE TITLE
my game crashed 

### ISSUE THREAD

**Issue by jojofenin99** [FiniteReality/embeddium#84]
here is the crash log 
[crash-2023-07-08_15.06.49-client.txt](https://github.com/embeddedt/embeddium/files/13193229/crash-2023-07-08_15.06.49-client.txt)
here is the normal log
[latest.log](https://github.com/embeddedt/embeddium/files/13193234/latest.log)

**Comment by embeddedt** [comment]
Crash seems to be caused by Diagonal Fences/Windows/Blocks, not Embeddium.

```
Caused by: java.lang.IllegalArgumentException: invalid model for diagonal block: diagonalfences:biomemakeover/blighted_balsa_fence#east=false,north=false,north_east=false,north_west=false,south=false,south_east=true,south_west=true,waterlogged=true,west=true
	at fuzs.diagonalblocks.api.v2.client.MultiPartTranslator.makeMultiPart(MultiPartTranslator.java:80) ~[diagonalblocks-forge-8.0.0.jar%23906!/:8.0.0]
	at fuzs.diagonalblocks.api.v2.client.MultiPartTranslator.getModelFromBase(MultiPartTranslator.java:73) ~[diagonalblocks-forge-8.0.0.jar%23906!/:8.0.0]
	at fuzs.diagonalblocks.api.v2.client.MultiPartTranslator.apply(MultiPartTranslator.java:69) ~[diagonalblocks-forge-8.0.0.jar%23906!/:8.0.0]
	at fuzs.diagonalblocks.client.handler.DiagonalModelHandler.onModifyUnbakedModel(DiagonalModelHandler.java:40) ~[diagonalblocks-forge-8.0.0.jar%23906!/:8.0.0]
	at fuzs.puzzleslib.impl.client.event.ForgeClientEventInvokers.lambda$register$86(ForgeClientEventInvokers.java:446) ~[PuzzlesLib-v8.1.2-1.20.1-Forge.jar%23734!/:8.1.2]
	at fuzs.puzzleslib.api.event.v1.core.ForgeEventInvokerRegistry.lambda$register$0(ForgeEventInvokerRegistry.java:25) ~[PuzzlesLib-v8.1.2-1.20.1-Forge.jar%23734!/:8.1.2]
	at fuzs.puzzleslib.impl.event.ForgeEventInvokerRegistryImpl$ForgeEventInvoker.lambda$register$1(ForgeEventInvokerRegistryImpl.java:722) ~[PuzzlesLib-v8.1.2-1.20.1-Forge.jar%23734!/:8.1.2]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.2.1.jar%23832!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$29(ModLoader.java:326) ~[fmlcore-1.20.1-47.2.1.jar%23831!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[fmlcore-1.20.1-47.2.1.jar%23831!/:?]
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326) ~[fmlcore-1.20.1-47.2.1.jar%23831!/:?]
	at net.minecraftforge.client.ForgeHooksClient.onModifyBakingResult(ForgeHooksClient.java:471) ~[forge-1.20.1-47.2.1-universal.jar%23835!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_245476_(ModelManager.java:174) ~[client-1.20.1-20230612.114412-srg.jar%23830!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_246937_(ModelManager.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23830!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```
