### ISSUE TITLE
Crash in MC 1.19.2

### ISSUE THREAD

**Issue by KatoNamus** [FiniteReality/embeddium#94]
Hello, my modpack crashed during a play session, crash log is pointing at Embeddium

Minecraft: 1.19.2
Forge: 43.3.0
Embeddium: embeddium-0.2.7+mc1.19.2.jar

```
Description: Unexpected error

java.util.NoSuchElementException: null
	at java.util.concurrent.ConcurrentLinkedDeque.screenNullResult(ConcurrentLinkedDeque.java:764) ~[?:?] {}
	at java.util.concurrent.ConcurrentLinkedDeque.removeFirst(ConcurrentLinkedDeque.java:959) ~[?:?] {}
	at java.util.concurrent.ConcurrentLinkedDeque.remove(ConcurrentLinkedDeque.java:1000) ~[?:?] {}
	at me.jellysquid.mods.sodium.common.util.collections.QueueDrainingIterator.next(QueueDrainingIterator.java:20) ~[embeddium-0.2.7+mc1.19.2.jar%23728!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.handlePendingFailures(RenderSectionManager.java:457) ~[embeddium-0.2.7+mc1.19.2.jar%23728!/:?] {re:mixin,re:classloading,pl:mixin:APP:betterfpsdist.mixins.json:Sodiummixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:378) ~[embeddium-0.2.7+mc1.19.2.jar%23728!/:?] {re:mixin,re:classloading,pl:mixin:APP:betterfpsdist.mixins.json:Sodiummixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:201) ~[embeddium-0.2.7+mc1.19.2.jar%23728!/:?] {re:mixin,re:classloading,pl:mixin:APP:vivecraft.sodium.mixins.json:SodiumWorldRendererVRMixin,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.m_194338_(LevelRenderer.java:7208) ~[client-1.19.2-20220805.130853-srg.jar%231027!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:adpother:coremod,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:adpother:coremod,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1158) ~[client-1.19.2-20220805.130853-srg.jar%231027!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:adpother:coremod,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:adpother:coremod,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%231027!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-textmc.json:MixinGameRenderer,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:tombstone.mixins.json:GameRendererMixin,pl:mixin:APP:ad_astra-common.mixins.json:client.GameRendererMixin,pl:mixin:APP:embeddiumplus.mixin.json:TotalDarkness.MixinGameRenderer,pl:mixin:APP:vivecraft.mixins.json:client_vr.renderer.GameRendererVRMixin,pl:mixin:APP:vivecraft.optifine.mixins.json:OptifineGamerRendererVRMixin,pl:mixin:APP:vivecraft.forge.mixins.json:ForgeGameRendererVRMixin,pl:mixin:APP:lodestone.mixins.json:GameRendererMixin,pl:mixin:APP:ars_nouveau.mixins.json:GameRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%231027!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-textmc.json:MixinGameRenderer,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:tombstone.mixins.json:GameRendererMixin,pl:mixin:APP:ad_astra-common.mixins.json:client.GameRendererMixin,pl:mixin:APP:embeddiumplus.mixin.json:TotalDarkness.MixinGameRenderer,pl:mixin:APP:vivecraft.mixins.json:client_vr.renderer.GameRendererVRMixin,pl:mixin:APP:vivecraft.optifine.mixins.json:OptifineGamerRendererVRMixin,pl:mixin:APP:vivecraft.forge.mixins.json:ForgeGameRendererVRMixin,pl:mixin:APP:lodestone.mixins.json:GameRendererMixin,pl:mixin:APP:ars_nouveau.mixins.json:GameRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%231027!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%231027!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%231027!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%231027!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.0.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
```

[Full crash-report on pastebin](https://pastebin.com/ZqWY4h4r)

I don't really have a lot of time to play, so not sure if I'll be able to test as soon as you compile a proposed fix, so.... This is my [custom modpack](https://www.dropbox.com/sh/e1evcgupb2esj4p/AAC4TnYwc0J96LambJ6izWB6a?dl=0) in case you might want to test it. It's exported with all debug.log and latest.log files generated today and the current save in case you just want to have a look at those.
You don't need to import it into CurseForge if you just want to look at the various logs. 
Vivecraft is currently inactive in the settings, so don't worry about that. (The only optimization I've done so far for VR was to throw a bunch of performance mods in and see which ones don't bring the whole house of cards down).

**Comment by embeddedt** [comment]
This issue is strange. It is caused by the "Translucent Face Sorting" option.  Embeddium's translucency sorting logic needs to read the buffers that Sodium normally sends to the GPU, but apparently some data doesn't exist when it should. I applied a bandaid fix for the issue in the [beta](https://nightly.link/embeddedt/embeddium/workflows/gradle/19.2%2Fforge/Embeddium.zip), but I would appreciate feedback on whether there are any visual issues.

> not sure if I'll be able to test as soon as you compile a proposed fix, so.... This is my custom modpack in case you might want to test it.

Unfortunately, I can't test full modpacks as they simply take too long to get things done with. I tried launching this one, and it took around 6 minutes. :upside_down_face: It's much easier to confirm issues are fixed if they can be reproduced in an isolated world with few mods.

**Comment by KatoNamus** [comment]
Good morning (from GMT+2/SAST). When I said I might not be able to test I didn't think the fix would be available this soon. As it is though, let's see what I can accomplish with it before the family gets back. I'll provide feedback a.s.a.p., thank you.

**Comment by KatoNamus** [comment]
Just loaded into that same world which is already an improvement as I couldn't load it anymore after that previous crash.
After running around for a few seconds I don't see any visual anomalies. I'll play it as long as I can and revert with feedback once I need to stop playing.

Thank you very much

**Comment by KatoNamus** [comment]
Looking very good, hasn't crashed with the update. Thank you very much once again.
